asr :
  demo : True
  model : jiwon65/whisper-small_korean-zeroth
beit3 :
  demo : True
  model : beit3_large_indomain_patch16_224_vqacustom
  model_path : ./beit3/finetune_checkpoint_large_indomain/checkpoint-best.pth
  sentencepiece_model : ./models/smp.model
  device : cuda
  dist_backend : nccl
  dist_url : env://
  drop_path : 0.15
  vocab_size : 64010
  checkpoint_activations : None
  model_key : model|module
  model_prefix : ''
  image_size : 224
  ans2label : ./answer2label.txt
tts:
  demo : True  
  tts_path: path